site_name: MkDocs Guide
site_url: https://blutterfly.github.io/mkdocs_guide

theme:
  name: material
  features:
    - navigation.sections
    - navigation.expand
    - search.suggest
    - content.code.copy
  palette:
    - scheme: default
      primary: teal
      accent: deep orange
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      primary: indigo
      accent: amber
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

nav:
  - Home: index.md
  - Guide:
    - Getting Started: guide/getting-started.md
    - Configuration: guide/configuration.md

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
